### ISSUE TITLE
issue iterating a list

### ISSUE THREAD

**Issue by dimitre** [jimmiebergmann/mini-yaml#17]
I'm parsing an YML file like this
```yml
name: build-emscripten

addons:
- git@github.com:dimitre/ofxMicroUI.git
- git@github.com:dimitre/ofxMicroUIMidiController.git

addons2: |
  git@github.com:dimitre/ofxMicroUI.git
  git@github.com:dimitre/ofxMicroUIMidiController.git

name2: build-emscripten2

```

and parsing with this code
```c++
        Node & addons = root["addons"];
		for(auto it = addons.Begin(); it != addons.End(); it++)
		{
			std::cout << (*it).first << ": " << (*it).second.As<string>() << std::endl;
		}
```
it seems to be iterating infinitely and not returning the values also
