### ISSUE TITLE
fails for (this example) object > list > object > string

### ISSUE THREAD

**Issue by g-pechorin** [jimmiebergmann/mini-yaml#18]
this chunk of yaml (geenrated by the library) doesn't load

```
hold: 
  7cc75dbb_d577_a943_8abc_97762b4e77d8: 
    windows: 
      - _class: editor
        _title: "assets##43c5c21b_98c4_a848_ac55_8642138e6e9d"
```

... and annoyingly it works without the quotes ...

```
hold: 
  7cc75dbb_d577_a943_8abc_97762b4e77d8: 
    windows: 
      - _class: editor
        _title: assets##43c5c21b_98c4_a848_ac55_8642138e6e9d
```
